version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.14
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./functions/package.json" }}
            - v1-dependencies-
 
      - run:
          name: Installing Dependencies
          working_directory: ~/project/functions
          command: yarn install

      - save_cache:
          paths:
            - ~/project/functions/node_modules
          key: v1-dependencies-{{ checksum "./functions/package.json" }}

      - run:
          name: Linting Build
          working_directory: ~/project/functions
          command: yarn lint

      - run:
          name: Running Tests
          working_directory: ~/project/functions
          command: yarn test
